### ISSUE TITLE
Vote Manager: Sending a voting batch to Lisk Hub with 'Phoenix1969' in it creates 'name doesn't exist'

### ISSUE THREAD

**Issue by tomploem** [lisk-builders/lisk-builders#63] opened 2018-09-22 12:04 UTC
**Steps to reproduce**

1. Select a few delegates in vote manager and make sure 'Phoenix1969' is in it
2. Select step1: .. and open it with Lisk Hub
3. You get an error: **Check spelling – name does not exist on mainnet**

**Comment by tomploem** [comment] 2018-09-22 12:31
No, the error is created when using these steps starting from the vote manager. There is no public repository for it so i created it here. 

Basically it starts when you want select certain delegates, for example **phoenix1969** in the vote manager.

**Comment by 4fryn** [comment] 2018-10-05 19:05
I can reproduce this. But it's not entirely clear what's causing this.

**Comment by 5an1ty** [comment] 2018-10-11 11:02
Cannot reproduce, seems to work.

**Comment by 4fryn** [comment] 2018-10-15 19:35
This is a Lisk Hub issue. I was able to reproduce it, and the reason is simply some hiccups in the API requests which looks up delegates on the network. If you run into this, simply retry clicking the STEP X button until it works.

**Comment by 4fryn** [comment] 2018-10-16 08:56
reported for lisk hub, probably not much we can do about it here

https://github.com/LiskHQ/lisk-hub/issues/1359

**Comment by 5an1ty** [comment] 2018-10-16 09:41
Thank you for looking into this. As it's no issue with our repository I'm closing this in favor of https://github.com/LiskHQ/lisk-hub/issues/1359.

**Closed by 5an1ty** 2018-10-16 09:41 UTC
